apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vr1i6uzkx-go
  janus-idp.io/tekton: vr1i6uzkx-go
  backstage.io/kubernetes-id: vr1i6uzkx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vr1i6uzkx-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
