apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vr1i6uzkx-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vr1i6uzkx-go 
  name: vr1i6uzkx-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vr1i6uzkx-go 
